# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

stages:
- stage: 'Build'
  displayName: 'Build the console application'
  jobs:
  - job: 'Build'
    displayName: 'Build job'

    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - template: Templates/Build.yml
      parameters:
        buildConfiguration: 'Debug'

    - template: Templates/Build.yml
      parameters:
        buildConfiguration: 'Release'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      condition: succeeded() 

- stage: 'Deploy'
  displayName: 'Deploy the calculator application'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: DEV
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: PublishBuildArtifacts@1
            displayName: 'Azure App Service Deploy: workstation'
            inputs:
              azureSubscription: 'Resource Manager - Tailspin - Space Game'
              appName: '$(CalculatorAppName)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'