<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Templates - Copy\**" />
    <EmbeddedResource Remove="Templates - Copy\**" />
    <None Remove="Templates - Copy\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>

</Project>
